class BaseUrl {
  // static String url = "http://192.168.43.38/be_project3/api/";
  static String url = "https://m2vrimuru.skom.id/api/be_project3/api/";
  // static String paths = "http://192.168.43.38/be_project3/images/";
  static String paths = "https://m2vrimuru.skom.id/api/be_project3/images/";
  static String urlLogin = url + "auth/login.php";
  static String urlDataDivisi = url + "divisi/data_divisi.php";
  static String urlTambahDivisi = url + "divisi/tambah_divisi.php";
  static String urlEditDivisi = url + "divisi/edit_divisi.php";
  static String urlHapusDivisi = url + "divisi/hapus_divisi.php";
  static String urlDataTeknisi = url + "teknisi/data_teknisi.php";
  static String urlTambahTeknisi = url + "teknisi/tambah_teknisi.php";
  static String urlEditTeknisi = url + "teknisi/edit_teknisi.php";
  static String urlHapusTeknisi = url + "teknisi/hapus_teknisi.php";
  static String urlDataGender = url + "gender/data_gender.php";
  static String urlDataKaryawan = url + "karyawan/data_user.php";
  static String urlTambahKaryawan = url + "karyawan/tambah_user.php";
  static String urlEditKaryawan = url + "karyawan/edit_user.php";
  static String urlHapusKaryawan = url + "karyawan/hapus_user.php";
  static String urlDataLvl = url + "level/data_level.php";
  static String urlGetTiket = url + "tiket/get_data_tiket.php?id_karyawan=";
  static String urlGetUsrTiket = url + "tiket/get_tiket_user.php?id_karyawan=";
  static String urlDataTiket = url + "tiket/data_tiket.php";
  static String urlTambahTiket = url + "tiket/tambah_tiket.php";
  static String urlTiketTeknisi = url + "tiket/get_tiket_teknisi.php";
  static String urlPerformaTeknisi = url + "teknisi/performa_teknisi.php";
  static String urlTiketOp = url + "tiket/get_tiket_op.php?id_teknisi=";
  static String urlcountTiket = url + "tiket/count_tiket.php?id_teknisi=";
  static String urleditTiket = url + "tiket/edit_tiket.php";
  static String urlAcctiket = url + "tiket/acc_tiket.php";
}
